"""add content_hash to knowledge_chunk

Revision ID: 443a7207995c
Revises: bb5863e5056e
Create Date: 2026-08-19 17:43:05.600772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '443a7207995c'
down_revision: Union[str, Sequence[str], None] = 'bb5863e5056e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Existing chunks have no content_hash and are fully regenerable by
    # re-running scripts/seed_knowledge_base.py, so clear them rather
    # than backfilling a fabricated hash value.
    op.execute('DELETE FROM knowledge_chunk')

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunk', sa.Column('content_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_index(op.f('ix_knowledge_chunk_content_hash'), 'knowledge_chunk', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunk_content_hash'), table_name='knowledge_chunk')
    op.drop_column('knowledge_chunk', 'content_hash')
    # ### end Alembic commands ###
