"""add knowledge_chunk table for rag

Revision ID: bb5863e5056e
Revises: 34ea9aec2e9c
Create Date: 2026-08-18 20:27:32.487812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'bb5863e5056e'
down_revision: Union[str, Sequence[str], None] = '34ea9aec2e9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('embedding', Vector(dim=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_chunk_category'), 'knowledge_chunk', ['category'], unique=False)
    op.create_index(op.f('ix_knowledge_chunk_source'), 'knowledge_chunk', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_chunk_source'), table_name='knowledge_chunk')
    op.drop_index(op.f('ix_knowledge_chunk_category'), table_name='knowledge_chunk')
    op.drop_table('knowledge_chunk')
    # ### end Alembic commands ###
